### ISSUE TITLE
change main function to azinja!

### ISSUE THREAD

**Issue by psycho-ir** [mr-hashemi/mr-hashemi#10]
A national programming language should have well defined combination of words!
I have to confess `bebin main` makes no sense and I believe we should change it ASAP to `bebin azinja` as a shortcut to `bebin Mr. Hashemi az inja shoroo kon`.

**Comment by yasharrashedi** [comment]
Although this change will not be backward compatible and will break existing software developed on current version, and requires a lot of effort for developers to upgrade, but the idead worth it, go ahead and do the change.

**Comment by psycho-ir** [comment]
Indeed it's not a backward compatible. 
However our current version is battle tested and I believe users won't need to upgrade for at least next 10 years, unless they care what their code is yelling.

**Comment by psycho-ir** [comment]
Released 🎉 
https://github.com/mr-hashemi/mr-hashemi/releases/tag/0.04
