### ISSUE TITLE
khoda vakili 100 toman midam!

### ISSUE THREAD

**Issue by byehack** [mr-hashemi/mr-hashemi#14]
to mano emtehan kon :)

**Comment by debian44** [comment]
وحشتناکه زبانت آقای هاشمی من ریدم سر در اون خراب شده ای که بخوان واسه این زبان بت پولم بدن

**Comment by byehack** [comment]
> وحشتناکه زبانت آقای هاشمی من ریدم سر در اون خراب شده ای که بخوان واسه این زبان بت پولم بدن

leader.ir based on Mr-Hashemi language!
