### ISSUE TITLE
Mr Hashemi supports integer division only (not float)

### ISSUE THREAD

**Issue by iamvee** [mr-hashemi/mr-hashemi#28]
this code works just fine (as an integer division problem though)
```java
bebin azinja () {
    v = 10 / 100;
    bechap(v  );

}
```

output:
```
0
```

while this one, does not work 
```java
bebin azinja () {
    v = 10.05 / 100;
    bechap(v  );

}
```
cannot get nothing in stdout .

@psycho-ir

**Comment by psycho-ir** [comment]
Mr. Hashemi just supports Big integers at the moment.

**Comment by iamvee** [comment]
any plan to support float numbers?

**Comment by psycho-ir** [comment]
Yes, will be part of Milestone 0.1

**Comment by psycho-ir** [comment]
It's been released!
