### ISSUE TITLE
نسخه ویندوز 32 بیتی

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [mr-hashemi/mr-hashemi#38]
سلام ، نسخه 32 بیتیش رو نداری؟

**Comment by psycho-ir** [comment]
نه متاسفانه

**Comment by MortezaRahmaniJRP** [comment]
هنوز سورس رو کامل نیگاش نکردم، ولی هر وقت وقت کردم میخوام رو نسخه 32 بیتیش کار کنم ببینم چه می شه کرد، البته با اجازت
