### ISSUE TITLE
input / voroodi

### ISSUE THREAD

**Issue by Gnkalk** [mr-hashemi/mr-hashemi#42]
زبان آقای هاشمی چیزی برای ورودی گرفتن یا به اصطلاح اینپوت داره؟

**Comment by Amirmohammadkazemi** [comment]
این زبان کتابخونه یا فریموورک نداره؟
#جدی

**Comment by Gnkalk** [comment]
یه سوال دیگه چرا زبانی ک از اون فورک کردید ورودی داره ولی زبون اقای هاشمی نداره؟ =)
