### ISSUE TITLE
ران نمیشه 

### ISSUE THREAD

**Issue by ArashIsDead** [mr-hashemi/mr-hashemi#49]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/92578649/185760314-53f8f33d-1be7-4617-bede-5053dc2549e0.png">

**Comment by XAliRezaMohseni** [comment]
سلام.
در سیستم های `Unix Like` مانند `MacOsX`، `Linux` و `BSD` شما باید فایل های اجرایی رو که درون `PATH`  سیستم قرار ندارند با یک `/.` پیش از نام فایل اجرا کنید.
برای مثال برای اجرای `hashemi` می‌نویسیم:
`./hashemi`

**Comment by XAliRezaMohseni** [comment]
لطفا پس از حل مشکل وضعیت رو به `Closed` تغییر دهید.

**Comment by ArashIsDead** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/92578649/185762580-b6d8e9f5-03b0-4f79-aaa1-f7deb181a078.png">

**Comment by XAliRezaMohseni** [comment]
اینجوری بنویسید:
`./hashem printer.hashem`

**Comment by amirdashtii** [comment]
~/Desktop/q  chmod +x ./hashem
~/Desktop/q  ls
hashem   q.hashem
~/Desktop/q  ./hashem q.hashem
zsh: exec format error: ./hashem

**Comment by Ali-Oliaee** [comment]
➜  Downloads ./hashem pakizegi.hashem
[1]    19593 segmentation fault (core dumped)  ./hashem pakizegi.hashem
➜  Downloads ls -la hashem
-rwxrwxrwx 1 ...

**Comment by XAliRezaMohseni** [comment]
>➜ Downloads ./hashem pakizegi.hashem
[1] 19593 segmentation fault (core dumped) ./hashem pakizegi.hashem
➜ Downloads ls -la hashem
-rwxrwxrwx 1 ...


[https://github.com/mr-hashemi/mr-hashemi/issues/47](url)

**Comment by XAliRezaMohseni** [comment]
>~/Desktop/q  chmod +x ./hashem
~/Desktop/q  ls
hashem q.hashem
~/Desktop/q  ./hashem q.hashem
zsh: exec format error: ./hashem


چه سیستم عاملی استفاده می‌کنید؟

**Comment by GroundedPhysics** [comment]
سلام خطای Core Dumped  اجرا نمیشه به وابستگی خاصی نیاز داره؟‌

**Comment by GroundedPhysics** [comment]
> سلام خطای Core Dumped اجرا نمیشه به وابستگی خاصی نیاز داره؟‌
و
لینک [https://github.com/mr-hashemi/mr-hashemi/issues/47](https://github.com/mr-hashemi/mr-hashemi/issues/url) موجود نیست!

**Comment by s-soroosh** [comment]
سلام

زبان برنامه‌نویسی آقای هاشمی فقط بر روی سیستم‌ عامل لینوکس قابل استفاده است.
