### ISSUE TITLE
اشتباه در مستند

### ISSUE THREAD

**Issue by mahdikarami8484** [mr-hashemi/mr-hashemi#50]
سلام وقت بخیر 
b += 1;
این در اجرا ارور میدهد ولی در مستند فارسی برای تا بود ازین استفاده شده.

```
bebin azinja(){
adadeMan = 0;  
majmoo = 0;  
  
ta (adadeMan<11) bood {  
    majmoo = majmoo + adadeMan;  
    adadeMan +=1;  
}  
  
bechap("majmoo barabar ast ba: "+majmoo);  }
```
```
Error(s) parsing script:
-- line 7 col 15: extraneous input '=' expecting {'(', BOOLEAN_LITERAL, STRING_LITERAL, IDENTIFIER, NUMERIC_LITERAL, FLOAT_LITERAL}
```

**Comment by manizn1382** [comment]
من هم این مشکل رو برای کد دب سلیب دارم

**Comment by mahdikarami8484** [comment]
> 

شما از 
b= b+1;
استفاده کنید

**Comment by mahdikarami8484** [comment]
> من هم این مشکل رو برای کد دب سلیب دارم

شما از 
b = b+1;
استفاده کنید

**Comment by s-soroosh** [comment]
ممنون از گزارش مشکل در مستند. اگر از کاربران کسی علاقه و وقتش رو داشت میتونه یه PR برای حل این مشکل در مستندات باز بکنه.

**Comment by mahdikarami8484** [comment]
مستند بروزرسانی شد
